Fix deploy_maven rule to be compatible with Python 3 (#186)
## What is the goal of this PR?

`deploy_maven` rule broke after we upgraded to `bazel 0.29.1` (and running it with Python 3) with the following exception:
```
Traceback (most recent call last):
  File "/home/circleci/.cache/bazel/_bazel_circleci/98db3734c28662e6d9e008d213a17afe/execroot/graknlabs_graql/bazel-out/k8-fastbuild/bin/grammar/deploy.py", line 163, in <module>
    pom_updated.write(pom_updated_content)
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

## What are the changes implemented in this PR?

Open all temporary files in write-text mode (`wt`) so we could write `str` to it (without first encoding to `bytes`)