Bugfix deploy_maven rule (#194)
## What is the goal of this PR?

Recent changes to `deploy_maven` broke it, causing to throw an exception of these kind:
```
Traceback (most recent call last):
  File "/home/circleci/.cache/bazel/_bazel_circleci/b86ecb3d15acddc9ce11cf216fed02f7/execroot/graknlabs_client_java/bazel-out/k8-fastbuild/bin/deploy.py", line 137, in <module>
    upload(maven_url, username, password, pom_file_path.name, filename_base + '.pom')
AttributeError: 'str' object has no attribute 'name'
```
This PR addresses this

## What are the changes implemented in this PR?

Treat `pom_file_path` as `str` so exception is not thrown.